# version: "3.9"

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: dockerfile.backend
#     image: vmsbot-backend:latest
#     container_name: vmsbot-backend
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env.development
#     environment:
#       - MONGO_URI=mongodb://host.docker.internal:27017
#       - MONGO_DB=vms_battery_health
#       - MONGO_COLLECTION=raw_gps_jan
#       - OLLAMA_URL=http://host.docker.internal:11434/api/generate
#     extra_hosts:
#       - "host.docker.internal:host-gateway"

#   frontend:
#     build:
#       context: .
#       dockerfile: dockerfile.frontend
#     image: vmsbot-frontend:latest
#     container_name: vmsbot-frontend
#     ports:
#       - "8501:8501"
#     environment:
#       - BACKEND_URL=http://backend:8000
#     depends_on:
#       - backend



services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    env_file:
      - .env.development
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    container_name: vmsbot-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    depends_on:
      mongodb:
        condition: service_healthy

    # 👇 IMPORTANT: allow access to host/external network properly
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: vmsbot-frontend
    restart: always
    ports:
      - "8501:8501"
    env_file:
      - .env.development
    depends_on:
      - backend

volumes:
  mongo_data: