FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/

# COPY ssl/fullchain.pem /app/fullchain.pem

# COPY ssl/privkey.pem /app/privkey.pem

ENV PORT=8080
EXPOSE ${PORT}
CMD ["sh", "-c", "if [ -s /app/ssl/fullchain.pem ] && [ -s /app/ssl/privkey.pem ]; then streamlit run app/streamlit_app.py --server.address=0.0.0.0 --server.port=${PORT} --server.sslCertFile=/app/ssl/fullchain.pem --server.sslKeyFile=/app/ssl/privkey.pem; else streamlit run app/streamlit_app.py --server.address=0.0.0.0 --server.port=${PORT}; fi"]