FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY main.py .

# COPY ssl/fullchain.pem /app/fullchain.pem

# COPY ssl/privkey.pem /app/privkey.pem
ENV PORT=8080
EXPOSE ${PORT}
CMD ["sh", "-c", "if [ -s /app/ssl/fullchain.pem ] && [ -s /app/ssl/privkey.pem ]; then uvicorn main:app --host 0.0.0.0 --port ${PORT} --ssl-keyfile=/app/ssl/privkey.pem --ssl-certfile=/app/ssl/fullchain.pem --timeout-keep-alive 3600; else uvicorn main:app --host 0.0.0.0 --port ${PORT} --timeout-keep-alive 3600; fi"]