FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY main.py .

# COPY ssl/fullchain.pem /app/fullchain.pem

# COPY ssl/privkey.pem /app/privkey.pem
 
EXPOSE 5007
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5007", "--timeout-keep-alive", "3600"]