services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    image: vmsbotbackend:latest
    container_name: vmsbot-backend
    ports:
      - "5007:5007"
    env_file:
      - .env.development
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    image: vmsbotfrontend:latest
    container_name: vmsbot-frontend
    ports:
      - "5008:5008"
    depends_on:
      - backend
    restart: unless-stopped